# Generated by Django 4.2.1 on 2023-05-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_cliente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.ForeignKey(blank=True, db_column='idGenero', null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.genero'),
        ),
    ]
